#+TITLE: SEDIT Mouse

* Introduction
The Interlisp-D editor SEDIT, from the Medley InterLisp system developed at Xerox-Parc, had mouse-bound structural editing commands.  This minor mode is an attempt to recreate those within emacs, as much as is practical.  See [[#Bindings][the Bindings section]].  See [[https://interlisp.org][interlisp]] for more info on SEDIT and the medley system in general.

* Terms
This software is released to the public domain

* Dependencies
The only dependency is [[https://github.com/magnars/expand-region.el][expand-region]].  This provides the main functionality of ~mouse-2~ (see [[#Bindings][Bindings]]).

* Bindings
:PROPERTIES:
:CUSTOM_ID: Bindings
:END:
For a complete guide of the original SEDIT, see [[https://drive.google.com/file/d/12LW5zCZauJvC63NRMJhjNv5qJkuuCflb/view][this document on google drive]].  Page 3 (Printed B-3) is where the mouse bindings start.  The bindings below were taken from the ~SEDITDEMO~ available on the medley system at [[https://interlisp.org][interlisp]].
** Plain Click
| Key       | Action                                    |
| ~mouse-1~ | Normal Selection                          |
| ~mouse-2~ | Select/Expand structure via [[https://github.com/magnars/expand-region.el][expand-region]] |
| ~mouse-3~ | Expand the region towards the click       |
** Mod/Drag & Click
| Key           | Action                                          |
| ~S-mouse-2~   | Copy structure and Yank in place                |
| ~C-mouse-2~   | Kill structure                                  |
| ~C-S-mouse-2~ | Move structure via ~mouse-drag-and-drop-region~ |

* Future improvements
** TODO Make ~C-S-mouse-2~ work as click-and-drag.
Currently works with two clicks instead of click, hold, release.

** TODO Make ~mouse-3~ single click closer to SEDIT function.
Currently covering the character selection case, but selecting by structures after a middle click will take some more work.

** IN-PROGRESS Make ~*-mouse-2~ do something WRT whitespace/newlines when yanking/killing/moving.
Currently testing ~sedit-auto-prettify-sexp~, which kills the defun and then passes ~current-kill~ to ~cl-prettyprint~.
SEDIT has the interlisp pretty-printer running interactively full time, so copying in sub-sexps automatically formats the entire sexp as you go.  Emacs *does not* have that, and the built-in pretty-printer gives less than satisfactory results (IMO).
